
###
GET http://localhost:9000/api/users HTTP/1.1,

###
GET http://localhost:9000/api/users/64b6e765a588e00cdbc8717d HTTP/1.1

###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
"firstName": "Maria",
"lastName": "Vargas",
"email": "mvgmail.com",
"password": "1258po",
"rol": "cliente"
}
###
GET http://localhost:9000/pqrs/pqrs HTTP/1.1
###
POST http://localhost:9000/pqrs/pqrs HTTP/1.1
Content-Type: application/json

{
"user": "64b71d90f5058019a5e316ca",
"type": "peticion",
"description": "Solicitud cancelación cuenta",
"date": "2023/07/19",
"area": "Atención al cliente",
"civilservant":["David", "Gabriel"],
"state":"radicada"
}

###
DELETE http://localhost:9000/pqrs/pqrs/64b6e916a588e00cdbc87188 HTTP/1.1

###
PUT http://localhost:9000/pqrs/edit/64b75dc7ac544e896eb3cdd4 HTTP/1.1
Content-Type: application/json

{
"state":"en tramite"
}
###
PUT  http://localhost:9000/pqrs/pqrs/64b70b639ada743e7b6e6b3c HTTP/1.1
Content-Type: application/json

{
"user": "64b6e7a2a588e00cdbc87180",
"type": "queja",
"description": "Mala facturación",
"date": "19/07/2023",
"area": "Facturación",
"civilservant":"Paula",
"state":"activa"
}
###
GET http://localhost:9000/pqrs/pqrs/64b6e916a588e00cdbc87188 HTTP/1.1

###
GET http://localhost:9000/pqrs/type/Solicitud HTTP/1.1
###
GET http://localhost:9000/pqrs/date/ HTTP/1.1

###
GET http://localhost:9000/pqrs/readt/queja HTTP/1.1

###
GET http://localhost:9000/pqrs/area/Atención_al_cliente HTTP/1.1


###
GET http://localhost:9000/pqrs/read/2023-07-18T05:00:00.000Z HTTP/1.1